platform :ios, '6.0'
pod 'AFNetworking', '1.1.0'
pod 'STLOAuth', '1.0.0'
pod 'Underscore.m', '~> 0.2.0'
pod 'ECSlidingViewController', '~> 0.9.0'
pod 'NUI', '~> 0.2.7'
pod 'RestKit/Testing', '~> 0.20.0'
pod 'RestKit', '~> 0.20.0'
pod 'AutoCoding', '~> 2.0.1'
pod 'cocoa-oauth'
pod 'SVProgressHUD'
